language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luasocket

script:
  - echo $LUA_PATH
  - cd tests
  - ./run_tests.sh
