language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - eval $(luarocks path --bin)
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix

install:
  - luarocks install luasocket
  - luarocks install luasql-sqlite3
  - luarocks install luacov
  - luarocks install cluacov
  - luarocks install luacov-coveralls

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

script:
  - ./run_tests.sh

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install
